### ISSUE TITLE
Bug? - Blocks and items disappear when broken

### ISSUE THREAD

**Issue by Nijoma69** [NerdHubMC/Refined-Machinery#1]
Hi,

Fantastic images, they look great ... really looking forward to trying a "proper" tech mod for 1.14

However ...

I've installed the following into an existing world and a new world to see if there was any difference: -

- AbusedLib-1.0.1
- Cardinal-Energy-1.0.0
- RefinedMachinery-1.0.0

With these mods installed anything I break (i.e. punching a tree to break a log) the broken item does not drop to the ground ready to be picked up, instead it simply disappears (much like when you punch something in creative mode).

If I remove just these mods both worlds (existing and newly generated) return to normal.

The other mods I'm using are: -

- AnimalNet-1.6+Fabric+19w11b.jar
- appleskin-mc1.14-fabric-1.0.5.jar
- beach-slimes-1.0.0+mc1.14.jar
- bettercompass-1.0.0-fabric.jar
- betterutilities-1.1.0.jar
- ClothEvents-0.3.1.23.jar
- CursedChests-1.1.11.jar
- durabilityviewer-1.14-fabric0.2.7-1.5.jar
- dwarfcoal-1.3.0.jar
- easierchests-1.14-fabric0.2.7-1.3.1.jar
- easiercrafting-1.14-fabric0.2.7-1.3.0.jar
- easyexcavate-1.4.1.jar
- fabric-0.2.7+build.127.jar
- fabric-furnaces-1.1.2.jar
- fabric-language-kotlin-1.3.30+build.2.jar
- FabricMagnet-1.14-1.0.1.jar
- foamfix-0.12.1.jar
- Harvest-1.14-fabric-1.0.4.jar
- Hwyla-fabric-1.14-1.9.16-60.jar
- illuminations-0.1.5-1.14.jar
- lead-villagers-1.0.0+mc1.14.jar
- leaf-decay-1.0.0.jar
- LeatherCows-1.0.0.19-universal.jar
- mousewheelie-1.1.3+1.14.jar
- REIAddons-1.1.0.jar
- Retro-Exchange-1.14-2.2.0.jar
- RoughlyEnoughItems-2.8.1.103.jar
- simpleteleporters-1.1.0-fabric.jar
- sodden-1.0.1.2.jar
- stockpile-1.0.3+1.14.jar
- Torcherino-0.7.47.jar
- TrampleStopper-1.0.0.22-universal.jar
- vanilla-hammers-1.1.4.jar
- vanilladeathchest-1.14-1.9.2.1-fabric.jar

Cheers

Nick

**Comment by alothmanmoe** [comment]
Hey, thanks for the bug report. I honestly hadn’t even thought of testing that as I didn’t know it would even be an issue, so I’ll take care of it as soon as I can today. I’ll be home in roughly 8 hours or so and then I can fix this and the recipe issue

**Comment by Nijoma69** [comment]
No probs buddy, glad to assist

**Comment by blasksun** [comment]
I second this bug. and it looks like RefinedMachinery is at fault here, because when removed tile drops return to normal.

**Comment by alothmanmoe** [comment]
Alright found the issue, should be a simple fix, it was the recipes causing it so as soon as i switch them over to json that should fix it

**Comment by alothmanmoe** [comment]
Alright, just pushed a fix onto the github, gonna work on some other bugs then get a release going,
https://github.com/NerdHubMC/Refined-Machinery/commit/898d791d0d85a4071373af8e79a3310830b712a2
