### ISSUE TITLE
Desync on server

### ISSUE THREAD

**Issue by Yoosk** [NerdHubMC/Refined-Machinery#10]
While playing on official [Fabric Ultimate](https://discordapp.com/channels/507304429255393322/507982666755473427/575488331945869323) server, two of us found out that connecting machines using link tool is visible to only one person who did it. Second one has to re-login in order to see changes.

**Comment by alothmanmoe** [comment]
Finally finished some of my other projects, so will take a look at this one later today. The only tricky thing is i need to find some way to test it as this is happening on server with multiple players.

**Comment by alothmanmoe** [comment]
Should now be fixed in https://github.com/NerdHubMC/Refined-Machinery/commit/33d0c6b027364f93a3517cc890f216a1c7b2e445

**Comment by alothmanmoe** [comment]
Last version for 1.14 just got released, waiting for curse to approve and working on 1.14.1
