### ISSUE TITLE
Minor Bug? - Retrieving dust from secondary output of pulveriser appears to be random

### ISSUE THREAD

**Issue by Nijoma69** [NerdHubMC/Refined-Machinery#11]
Hi,

Loving this mod, exactly what MC 1.14 needed ...

So ... I think I've noticed a very minor bug with the secondary output of the pulveriser.

When pulverising iron ore I'm able to click on the iron dust and retrieve it from the primary output slot, however if I then click on the nickel dust in the secondary output slot it seems to be random as to whether I actually retrieve nickel dust or it simply just disappears.

I've not yet tested this against other ores but it is definitely repeatable with iron ore, again a very minor bug but at least if you're aware it can be added to the list.

Regards

Nick

**Comment by alothmanmoe** [comment]
Should now be fixed, i still have a few more things i'd like to do before a release, but hopefully will have one out today

**Comment by alothmanmoe** [comment]
Last version for 1.14 just got released, waiting for curse to approve and working on 1.14.1
