### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SDUBZ** [NerdHubMC/Refined-Machinery#12]
what levels do ores gen on ?
and has anyone had problems with ores not spawning ?

**Comment by alothmanmoe** [comment]
Seems like a lot of people are saying that ores spawn rates are really low, will be changing some values as well as adding a config option to allow people to change it too

**Comment by SDUBZ** [comment]
yeah they all seem super rare

**Comment by SDUBZ** [comment]
Also i was wondering if you could help me with https://minecraft.curseforge.com/projects/miners-horizon trying to get the necessary ids and such for your mods ores but having troubles
 eg how they do block spawns of ore
{
      "blockIdentifier": {
        "field_13353": "minecraft",
        "field_13355": "coal_ore"
      },
      "size": 17,
      "count": 20,
      "bottomOffset": 100,
      "topOffset": 0,
      "maxY": 256
    },

**Comment by jessiewestlake** [comment]
I haven't had any problems with ore rates. Everything seems pretty plentiful except Lead, which is probably intentional? I had to travel to a part of my map which wasn't previously generated because the world existed before the mod was added.

**Comment by SDUBZ** [comment]
@jessiewestlake im talking for server not just singleplayer world

**Comment by SDUBZ** [comment]
is refined machinery gonna be ready for 1.14.1 api ?

**Comment by alothmanmoe** [comment]
Not yet, updating it to 1.14.1 will be easy but I can’t work on it atm due to not having my desktop setup. Also there is a discord server if you’d like to join for any questions or help with anything for faster responses

**Comment by SDUBZ** [comment]
Thank you for your work so far , and i thught i would ask juts incase you get many people wondering the same that isnt in your discord :)

**Comment by alothmanmoe** [comment]
Last version for 1.14 just got released, waiting for curse to approve and working on 1.14.1
