### ISSUE TITLE
Crashes imediatly / solved

### ISSUE THREAD

**Issue by Bi0fall** [NerdHubMC/Refined-Machinery#15]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!

**Comment by alothmanmoe** [comment]
Could you provide the full log? Usually al issues from this means you probably downloaded the wrong AbusedLib version that’s for 1.12 not 1.14

**Comment by Bi0fall** [comment]
ah i see that was an oversight on my part thank you.

**Comment by Bi0fall** [comment]
u

**Comment by Bi0fall** [comment]
solved above
