### ISSUE TITLE
Pulverizer ideas

### ISSUE THREAD

**Issue by Dragonracer1973** [NerdHubMC/Refined-Machinery#16]
been thinking abit, it be cool to have the pulverizer make cobble into gravel, and gravel into sand

**Comment by alothmanmoe** [comment]
Those recipes already exist 🤔 

`registerRecipe(new ItemStack(Blocks.STONE), new ItemStack(Blocks.COBBLESTONE), ItemStack.EMPTY, 0);
            registerRecipe(new ItemStack(Blocks.COBBLESTONE), new ItemStack(Blocks.GRAVEL), new ItemStack(Blocks.SAND), 15);
            registerRecipe(new ItemStack(Blocks.NETHERRACK), new ItemStack(Blocks.GRAVEL), ItemStack.EMPTY, 0);
            registerRecipe(new ItemStack(Blocks.GRAVEL), new ItemStack(Blocks.SAND), new ItemStack(Items.FLINT), 15);
            registerRecipe(new ItemStack(Blocks.SANDSTONE), new ItemStack(Blocks.SAND, 2), ItemStack.EMPTY, 0);
            registerRecipe(new ItemStack(Blocks.SMOOTH_SANDSTONE), new ItemStack(Blocks.SAND, 2), ItemStack.EMPTY, 0);
            registerRecipe(new ItemStack(Blocks.CHISELED_SANDSTONE), new ItemStack(Blocks.SAND, 2), ItemStack.EMPTY, 0);
            registerRecipe(new ItemStack(Blocks.CLAY), new ItemStack(Items.CLAY_BALL, 4), ItemStack.EMPTY, 0);`

**Comment by alothmanmoe** [comment]
Last version for 1.14 just got released, waiting for curse to approve and working on 1.14.1

(Also pulverizer recipes are now json, so anyone can add/edit them)
