### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors!

### ISSUE THREAD

**Issue by AllegoricSiren** [NerdHubMC/Refined-Machinery#19]
Sorry if you saw the previous post I made, I didn't mean to send it. Anyways
[crash-2019-05-23_17.20.10-client.pdf](https://github.com/NerdHubMC/Refined-Machinery/files/3214246/crash-2019-05-23_17.20.10-client.pdf)
Thats the link to my crash report, I got no clue what to do. Not too sure how to read the code but I've had this problem with other mods too. I tried a couple different version but none of them had a different effect. Help would be much appreciated.

**Comment by alothmanmoe** [comment]
It's fine. But the mod does not yet support 1.14.1 which is why its crashing.
