### ISSUE TITLE
Some other bugs

### ISSUE THREAD

**Issue by LeQwouincy** [NerdHubMC/Refined-Machinery#2]
Mods running :
AbusedLib-1.0.1
Cardinal-Energy-1.0.0
RefinedMachinery-1.0.0

Firstly, the mod seems like it will be a really great mod for automation ! Plus it has a really good design. 
But also seems like there is still many bugs. I have made few tests in survival and creative, so here is what i have found :

- Same as the report #1 (https://github.com/NerdHubMC/Refined-Machinery/issues/1)

- Dusts can't be smelted (or perhaps it's meant to be like that)

-Many item get duplicated while shift click in UI of machines

-Also happen with hopper

-Fluid pump cause game's crash 

-Sword charge stop going down under 1000 and keep it's high damages

That's all i have noticed. Perhaps It's due to my config or some of those bugs are linked. I let this part for you.

 Thanks for working on this mod, I know this is only the beginning.
i'm looking forward to see it progress.
Good luck !

**Comment by alothmanmoe** [comment]
Thanks for the bug report, i've gone ahead and fixed the recipe and dust issues, now just going to go through the other few you've added here. I've personally not had the fluid pump crash on me, so taking a look at what might cause it, will see whats up with that

**Comment by alothmanmoe** [comment]
Woop, seems like i found the cause of the crash, was simply that i was using the wrong position to check for... Will have that fixed as well

**Comment by alothmanmoe** [comment]
All these should now be fixed, thanks!
