### ISSUE TITLE
crash on viewing steel

### ISSUE THREAD

**Issue by amberwillow** [NerdHubMC/Refined-Machinery#21]
Hey there, thanks for updating to 1.14.1

I got a bit of a problem with it though, after smelting the iron into steel, the game crashes upon viewing the steel ingot. The game does not crash upon creation, but upon witnessing it (quantum minecraft?). I've tested it with both a hopper leading to a chest and in the blast furnace itself. Interestingly, when looking at the blastfurnace while a hopper is attached, i see the steel for a fraction of a second before its piped on to the chest, no crash there. Also, before the game crashes i do see the icon for steel there shortly (like, a 10th of a second, just enough to realize its there) and the server goes down. I've tried the same in singleplayer, and there the entire client crashes under the same circumstances.

 here's the (now full) log that goes with it:

https://pastebin.com/fng7Lx9U

**Comment by UpcraftLP** [comment]
try updating cardinal components and cardinal energy, if the issue persists please send a new log ;)

**Comment by amberwillow** [comment]
Thanks, that did it!
Your current description says we need neither though (cardinal energy is included, components I've not seen mentioned in it at all?). So I'm curious, is this because of the other mods I'm running?

**Comment by poboy975** [comment]
I'm having this same issue, and I've installed the latest cardinal energy and abused lib. Here the full crash report.

https://pastebin.com/CpFD0npK

edit

Nevermind, I missed the cardinal components update, it's working now
