### ISSUE TITLE
Fluid Pump Crash

### ISSUE THREAD

**Issue by 1a2s3d4f1** [NerdHubMC/Refined-Machinery#22]
https://paste.ubuntu.com/p/YfCf7M4mzQ/
Use Fluid Pump pump water and lava  game crash

**Comment by alothmanmoe** [comment]
Will have to take a look at this tomorrow as it's getting pretty late, but be sure to update abusedlib and cardinal energy as you're on outdated versions, those could also be the cause. If they aren't ill figure out what's going on in the morning

**Comment by 1a2s3d4f1** [comment]
In Minecraft1.14.1 Quarry is not work，Energy item convulsion
Abusedlib v1.1.0
Cardinal Energy v1.1.0

**Comment by alothmanmoe** [comment]
Just tested, and the quarry does actually work, but you have to reload the world after you start it. Simple client desync that i can fix today
