### ISSUE TITLE
Doesnt charge anything in Server

### ISSUE THREAD

**Issue by BigMandigo** [NerdHubMC/Refined-Machinery#23]
Works great in solo but In a fabric server it doesnt want to charge steel or sword. Been on creative on the sever to do some test but no results. It flickers 0 to 50 very fast back and forth. Energy bar is maxed

**Comment by alothmanmoe** [comment]
Yup, working on a fix right now

**Comment by BigMandigo** [comment]
> 
> 
> Yup, working on a fix right now

are you guys going to continue making 1.14 version or just going with 1.14.1?

**Comment by alothmanmoe** [comment]
Nah 1.14 is no longer supported, i only pushed a hotfix version on there as there were tons of bugs. As of now its 1.14.1. It makes it more tedious to support multiple versions at once, especially considering the next update is gonna be the "Content Overhaul" update
