### ISSUE TITLE
Quarry has "No mining Coordinates"

### ISSUE THREAD

**Issue by poboy975** [NerdHubMC/Refined-Machinery#24]
So, I think this is a bug, I've tried in a survival and creative world. I can't get the quarry to run. I can mark the area, and when I put the card in the quarry, the glowing lines appear to show the marked area, but the quarry has a "no mining coordinates" message floating on top, and even after right clicking, and seeing the animation inside of the tools rotating, nothing happens. I've tried solar panels right next to the quarry, and solar panels connected by energy cables. The quarry gets power, but it's not actually doing mining. 

List of currently installed mods:
![CurrentMods](https://user-images.githubusercontent.com/249487/58379765-65ed8480-7f65-11e9-9c50-ba6b8b304e6b.png)

**Comment by alothmanmoe** [comment]
Yup, refer to https://github.com/NerdHubMC/Refined-Machinery/issues/22#issuecomment-495922191
