### ISSUE TITLE
Energized Sword stops working

### ISSUE THREAD

**Issue by poboy975** [NerdHubMC/Refined-Machinery#25]
This isn't causing a crash like the other energized sword issue, so far as I can tell, I've not tried to put it in a anvil. But after logging into the game this morning, the energized sword no longer works. First thing I noticed was that it isn't appearing in right hand like a normal tool, and the energy is zero with mouse over, but the energy bar shows full. I put it in a charger to recharge thinking that was why it wasn't working, but after recharging, it still doesn't show up in my hand, and doesn't actually hit any mobs.

btw, I love what you've got so far in this mod

**Comment by alothmanmoe** [comment]
Thanks! This issue has actually already been fixed, it was a cardinal energy bug, new update is being worked on

**Comment by UpcraftLP** [comment]
@poboy975 just put cardinal components v1.1.2 into your mods folder for now, that will fix it.

**Comment by poboy975** [comment]
Where do I find the 1.1.2 version? I don't see it on curseforge

**Comment by alothmanmoe** [comment]
Seems like upcraft hasnt uploaded to curse, but for now: https://maven.abusedmaster.xyz/com/github/NerdHubMC/Cardinal-Components-API/1.1.2/Cardinal-Components-API-1.1.2.jar

**Comment by poboy975** [comment]
I downloaded and installed that version, but I get this error when I try to run minecraft

https://pastebin.com/66SRQeTT

**Comment by UpcraftLP** [comment]
you have some corrupt file, try redownloading.
