### ISSUE TITLE
Block Exchanger and Steel animation bug, Steel "fake dupes" glitch

### ISSUE THREAD

**Issue by rzv04** [NerdHubMC/Refined-Machinery#26]
For me. selecting Block Exchanger and Steel in main hand doesn't show the item, it bounces back and forth "outside" of the hand, so I can't see the item; Energized Sword is rotated 90 degrees and its animation is also bugged.
Steel has some issues when shift-clicking it in any chest, inventory, etc. and it "fake dupes"/a ghost item appears.Sometimes, Steel can't be stacked.

Tested on a 2 player Server; MC 1.14.1 fabric loader for vanilla
Mods used (including Fabric API) : https://imgur.com/a/w2rSUrs
Screenshots with the Block Exchanger and Energized Sword animation bugs: https://imgur.com/a/4DG7nQ6
https://imgur.com/a/edMCJWl
https://imgur.com/a/vLju9m4

Also, this was recently posted, but in a server, the energy system glitches out and displays 0 CE even if Energized Sword or Block Exchanger are recharged

**Comment by alothmanmoe** [comment]
Yeah, these bugs were caused by Cardinal Components, and have been fixed, i'll have an update out as soon as i can
