### ISSUE TITLE
Farmer only fills first output slot

### ISSUE THREAD

**Issue by angelnc1989** [NerdHubMC/Refined-Machinery#27]
The farmer stops working when the first output slot is full and doesn't use the other slots.
![image](https://user-images.githubusercontent.com/5382585/58412915-cb319a80-8077-11e9-9cc7-2b44780efd04.png)

It also doesn't produce any seeds once at least one seed is in the seed input slot,

**Comment by alothmanmoe** [comment]
Taking a look at this now!
