### ISSUE TITLE
Quarry Starting over

### ISSUE THREAD

**Issue by poboy975** [NerdHubMC/Refined-Machinery#31]
This seems to be, maybe not a bug, just not implemented. I use the Minor's Horizon dimension for mining, and when I leave and return, the quarry starts over from the top, including mining all the block coordinates that have already been mined. With a large area defined, that's a lot of time to get back to coords that actually have blocks in them.

Also, as a feature, would it be possible in the future to speed up the quarry speed at the cost of more CE?

**Comment by alothmanmoe** [comment]
So how the quarry works is as soon as you define all the mining positions, it’ll actually go through and cache the entire mining area into its nbt data. This should mean that it doesn’t need to start over as it continues with the current area. I’ve not personally seen an issue with this so I’ll need to look into it. As for upgrades, they’re actually coming in the next update!

**Comment by poboy975** [comment]
Well, I stayed there afk for a couple of hours, the quarry was going through coords, but it didn't actually mine anything. Until I removed the card and redefined the area and replaced it. Didn't crash or anything. Plenty of power with 4 tier 3 solar panels.

Cool, looking forward to upgrades!

**Comment by alothmanmoe** [comment]
Should now be fixed in the latest update (at least i hope, worked fine on my end) so releasing a version in a few mins here
