### ISSUE TITLE
Quarry only doing one level.

### ISSUE THREAD

**Issue by Madshawn65** [NerdHubMC/Refined-Machinery#32]
Set the corners.  Doesn't start.  Quit and start again like you suggested in another post and it starts working but only does one level. The grid is only one level deep.
  Took abused lib and cardinal energy jar files out since the curse forge page says those are included now.  Broke the first block.  After that, coords are going through the quarry like it's working, but not breaking blocks.  Grid is still one level deep.
  Just started using these mods over the weekend so maybe I'm doing something wrong?

**Comment by Madshawn65** [comment]
Using 1.14.1.

**Comment by alothmanmoe** [comment]
Was fixed in new version
