### ISSUE TITLE
1.14.2 Refined Machinery 1.1.0_1.14.1-Fabric(steel ingot not charging)

### ISSUE THREAD

**Issue by SDUBZ** [NerdHubMC/Refined-Machinery#33]
when i put steel in charger it doesnt put any energy into ingot but drains all the energy out of chrager

**Comment by Napkin** [comment]
It works for me in a single-player world but not on a dedicated server.

**Comment by Napkin** [comment]
This is probably a duplicate of https://github.com/NerdHubMC/Refined-Machinery/issues/23.
