### ISSUE TITLE
1.1.1 version still shows 0 CE for Block Exchanger

### ISSUE THREAD

**Issue by rzv04** [NerdHubMC/Refined-Machinery#35]
So the update at a first glance really fixed bugs, but the energy bug is still not fixed for me with version 1.1.1 mc 1.14.2 server, do I need to upgrade from fabric-api-0.3.0-pre+build.157a ?
SS https://imgur.com/a/U6SfoT8

**Comment by alothmanmoe** [comment]
fixed, update is on curse in a few mins
