### ISSUE TITLE
Steel not charging normally

### ISSUE THREAD

**Issue by amberwillow** [NerdHubMC/Refined-Machinery#36]
Something weird is going on with charging steel. I'm not getting back errors or crashes, but under certain circumstances it will not charge in the charger

From what I've seen so far: A stack will charge. A split stack will not. Single steel ingots dont seem to charge at all.

Also, I get ghost images when i try to move/stack them in my inventory, they seem to be in the old AND the new spot, until i close my inventory and reopen and they'll be where they ought to be.

As I did get some charged steel, i went on and made the wings - when i put those in the charger it IS transferring, but durability and not energy. Maybe related to the steel charging?

As I said, there are no errors, but for the sake of being complete, here's the logs:
http://www.rosered.org/mc/clientlog.log
http://www.rosered.org/mc/serverlog.log

**Comment by alothmanmoe** [comment]
fixed, update is on curse in a few mins
