### ISSUE TITLE
steel cant store enough energy to

### ISSUE THREAD

**Issue by gravysamich** [NerdHubMC/Refined-Machinery#37]
steel doesn't charge right. it gets to about 32000 energy and it rolls over to -32000.

this means i cant get energized steel.

**Comment by alothmanmoe** [comment]
Which version of the mod are you on?

**Comment by gravysamich** [comment]
im on the most recent version.

but i just realized that it is just a visual bug. the steel is still storing energy it just doesn't display correctly when it is still in the charger. once remove it is correct.

**Comment by Napkin** [comment]
Same here with RefinedMachinery-1.1.2.jar.
Looks like the ingot is charging properly but whenever put into the energy charger the tool-tip shows wrong information. So you need to take it out to see the current correct charge.

**Comment by alothmanmoe** [comment]
Should now be fixed
