### ISSUE TITLE
Advancements gone?

### ISSUE THREAD

**Issue by Napkin** [NerdHubMC/Refined-Machinery#4]
After installing, the server console was spammed by many messages like this:

> [Server thread/WARN]: Ignored advancement 'minecraft:adventure/adventuring_time' in progress file /home/chojin/Games/MultiMC/instances/Fabric 1.14/.minecraft/saves/New World/advancements/5edab215-f16b-4b10-94a2-ea0df8ed7062.json - it doesn't exist anymore?

And indeed, can't get advancements to work in my world anymore. I guess it's related to one of Cardinal-Energy, AbusedLib or RefinedMachinery.

Any more info I can provide? Cheers!

**Comment by alothmanmoe** [comment]
Fixed in https://github.com/NerdHubMC/Refined-Machinery/commit/898d791d0d85a4071373af8e79a3310830b712a2
I'll get an update out soon as i finish fixing a few other things
