### ISSUE TITLE
Crash when searching Copper Ore Usage

### ISSUE THREAD

**Issue by SihenZhang** [NerdHubMC/Refined-Machinery#42]
Minecraft Version: 1.14.2
Fabric Loader Version: 0.4.8-build.154
Fabric API Version: 0.3.0-build.179
Mod Version: 1.1.2
REI Version: 2.9.4-build.126
SinglePlayer/MultiPlayer: MultiPlayer
Crash Report: https://paste.ubuntu.com/p/TyVjmv5Bd4/
How to Reproduce: 
1. Press "U" on a Copper Ore; 
2. Click "Pulverizer Recipe"; 
3. Press "Esc" to exit; 
4. Repeat 1 - 3 several times

**Comment by shedaniel** [comment]
Please report this on REI repo instead.
