### ISSUE TITLE
Placed a Quarry Recorder in a Quarry

### ISSUE THREAD

**Issue by Luxley** [NerdHubMC/Refined-Machinery#45]
I placed a Recorder with Coords into the Quarry on my Multiplayer server. And was forcbly disconnected with the following screenshot

![image](https://user-images.githubusercontent.com/50896979/59373199-cc68f580-8d0e-11e9-9e45-1562f223c917.png)

And now unable to log back on, due to the Quarry and recorder

**Comment by kaffeekirsche** [comment]
Have the same problem. The region I marked is too big.
Would it be possible to create a security query in the code that prevents you from marking too large a range?

**Comment by alothmanmoe** [comment]
Fixed, data is now saved on the world so the size should no longer matter
