### ISSUE TITLE
Suggestion Energized Steel

### ISSUE THREAD

**Issue by FloraAndu** [NerdHubMC/Refined-Machinery#46]
The process to energize steel requires 500k energy and it does so by stacks at a time. I think that it would be a lot better to reduce the energy requirement and make the output 1 bar at a time because charging to 500k takes a lot of time while I only need 1 energized steel.

**Comment by UpcraftLP** [comment]
you are actually meant to only charge one item at a time, not a full stack

**Comment by alothmanmoe** [comment]
Recipes and values will be changing soon to make the mod more balanced :D
