### ISSUE TITLE
Suggestion - Compatibility with Simple Pipes (fabric)

### ISSUE THREAD

**Issue by 1a2s3d4f1** [NerdHubMC/Refined-Machinery#50]
The fluid pipe is not link fluid tank.   
[Simple Pipes](https://minecraft.curseforge.com/projects/simplepipes)
[libblockattributes](https://minecraft.curseforge.com/projects/libblockattributes)
could you compatibility Simple Pipes ?

**Comment by alothmanmoe** [comment]
I currently use my own fluid system, i will soon create a component for it using Cardinal Components so that other mods can interact with them.
