### ISSUE TITLE
1.14.2 Instructions to transfer energy don't work

### ISSUE THREAD

**Issue by JustJinxed** [NerdHubMC/Refined-Machinery#51]
I'm using the linking tool as directed on the wiki, and none of the machine power up. Even placing a solar cell, the collectors don't attach to the cell, they attach to the ground?

**Comment by JustJinxed** [comment]
I'm using the linking tool as directed on the wiki, and none of the machine power up. Even placing a solar cell, the collectors don't attach to the cell, they attach to the ground?

**Comment by alothmanmoe** [comment]
Fixed, was a bug i had but its all good now
