### ISSUE TITLE
Severe Crash - Unknown Cause - Other Mods Present

### ISSUE THREAD

**Issue by Rahmiel** [NerdHubMC/Refined-Machinery#52]
**Issue:** The game crashes on load with Refined Machinery installed. Though I am sure that it is a conflict, I can't read the config myself as I'm somewhat confused by some of the outputs (I just started using Fabric instead of Forge).

Also I can be an idiot and completely miss simple things, if I did please point them out instead of just closing the issue. I would appreciate feedback so I can fix things on my end.

Using MultiMC and Fabric build 187 (newest on curseforge).

As I can't really explain much further, here is the log, hope we can help each other.

https://paste.ee/p/d44MO

Edit1: From what I can see, I believe the issue is being caused by Optifabric (and Optifine ofcrs). I'm assuming it has something to do with block tessellation or something, but I'm still testing.

Edit2: Can confirm it is Optifabric (Optifine). I'm going to keep digging myself if I can.

**Comment by Rahmiel** [comment]
To further clarify, the setup (mods, versions, and launcher) that I am using works fine without RM installed. I'm really interested in adding this mod for a few of its utilities, and the possibility of playing with a mod destined to grow up in an era that doesn't rely on Forge.

**Comment by shedaniel** [comment]
Try removing optifine.

**Comment by Rahmiel** [comment]
As stated in the edit, that does fix the problem, however, it introduces a new problem for my private modpack. My server relies heavily on vanilla farms, some of which require optifine for players to actually be able to play the game (blazes are one big culprit). We can play with minimal particles which helps the issue, but again that is only a bandaid. Is there a specific setting in Optifine that would cause this issue?

Edit1: Or another mod, way to disable specific particles, reduce framerate lag with high volumes of mobs and entities?

**Comment by UpcraftLP** [comment]
take this to the [OptiFabric issue tracker](https://github.com/modmuss50/OptiFabric/issues)
