### ISSUE TITLE
Build failure due to javafx import

### ISSUE THREAD

**Issue by vpzomtrrfrt** [NerdHubMC/Refined-Machinery#55]
When I try to run `gradle build`, it fails with this error:
```
/home/colin/Refined-Machinery/src/main/java/abused_master/refinedmachinery/tiles/machine/BlockEntityVacuum.java:6: error: package javafx.geometry does not exist
```
This import doesn't appear to actually be used, so I assume it would be fine to remove it

**Comment by alothmanmoe** [comment]
Wait what, I removed all javafx.geometry usages a while ago, why is this a thing XD, but yeah should be removed

**Comment by alothmanmoe** [comment]
Fixed in https://github.com/NerdHubMC/Refined-Machinery/commit/5ab47a3a0c90b0e7401a98ba8886f6f14f79f34a
