### ISSUE TITLE
[Suggestion] Make the Disenchanter use books as a secondary input

### ISSUE THREAD

**Issue by angelnc1989** [NerdHubMC/Refined-Machinery#9]
Right now the Disenchanter is generating books out of nothing. It would be nice to have it consume books for every enchant it takes off an item.

**Comment by alothmanmoe** [comment]
Will do actually, didn't think of this earlier

**Comment by alothmanmoe** [comment]
Added in https://github.com/NerdHubMC/Refined-Machinery/commit/e0d45091ac951289bfe9319af232b0bff6cd84a8

**Comment by alothmanmoe** [comment]
Last version for 1.14 just got released, waiting for curse to approve and working on 1.14.1
